### ISSUE TITLE
Not Deploying

### ISSUE THREAD

**Issue by connorwinston** [jakejarvis/firebase-deploy-action#3]
I am trying to use this to automate the deployment of my Firebase Project. However, it is not deploying to Firebase. Here are my logs for the run deploy action... It is all coming up as passed. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/12714889/68102058-8f0c2c80-fe96-11e9-8b35-ae47f1299f96.png)

[logs_2.zip](https://github.com/jakejarvis/firebase-deploy-action/files/3802785/logs_2.zip)

**Comment by Kiricon** [comment]
Having the same issue when using the default config in the example

**Comment by joaomantovani** [comment]
Same

**Comment by andreasvirkus** [comment]
+1 on this

**Comment by vicrodri** [comment]
+1 Same here

**Comment by andreasvirkus** [comment]
FYI This action deploys fine; switched for now
https://github.com/marketplace/actions/github-action-for-firebase

**Comment by vicrodri** [comment]
@andreasvirkus worked like a charm ty
